name: noseinwetpussy
on:
  workflow_dispatch: {}
  push:
    branches:
      - sn
  permissions: read-all|write-all
  
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: sn
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.8.2
